### ISSUE TITLE
Install fails because /data/plugins/music_service/squeezelite doesn't exist

### ISSUE THREAD

**Issue by oakbrad** [Saiyato/volumio-squeezelite-plugin#4]
I've got a fresh install of Volumio 2.779 on a Raspberry Pi 3. Installing from the Plugins menu does not work, so I did a manual install by cloning the repo. I'm getting this error when I run install.sh

```Installing Squeezelite and its dependencies...
Downloading squeezelite...
converted 'https://github.com/Saiyato/volumio-squeezelite-plugin/raw/master/known_working_versions/squeezelite-armv6hf-volumio' (ANSI_X3.4-1968) -> 'https://github.com/Saiyato/volumio-squeezelite-plugin/raw/master/known_working_versions/squeezelite-armv6hf-volumio' (UTF-8)
--2020-06-15 02:42:16--  https://github.com/Saiyato/volumio-squeezelite-plugin/raw/master/known_working_versions/squeezelite-armv6hf-volumio
Resolving github.com (github.com)... 192.30.255.112
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/Saiyato/volumio-squeezelite-plugin/master/known_working_versions/squeezelite-armv6hf-volumio [following]
converted 'https://raw.githubusercontent.com/Saiyato/volumio-squeezelite-plugin/master/known_working_versions/squeezelite-armv6hf-volumio' (ANSI_X3.4-1968) -> 'https://raw.githubusercontent.com/Saiyato/volumio-squeezelite-plugin/master/known_working_versions/squeezelite-armv6hf-volumio' (UTF-8)
--2020-06-15 02:42:16--  https://raw.githubusercontent.com/Saiyato/volumio-squeezelite-plugin/master/known_working_versions/squeezelite-armv6hf-volumio
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.192.133, 151.101.64.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 159912 (156K) [application/octet-stream]
Saving to: '/opt/squeezelite'

/opt/squeezelite    100%[=====================>] 156.16K  --.-KB/s   in 0.1s   

2020-06-15 02:42:16 (1.32 MB/s) - '/opt/squeezelite' saved [159912/159912]

/data/plugins/music_service/squeezelite/squeezelite.service: No such file or directory
chown: cannot access '/data/plugins/music_service/squeezelite/squeezelite.service': No such file or directory
sed: can't read /data/plugins/music_service/squeezelite/squeezelite.service: No such file or directory
sed: can't read /data/plugins/music_service/squeezelite/squeezelite.service: No such file or directory
sed: can't read /data/plugins/music_service/squeezelite/squeezelite.service: No such file or directory
sed: can't read /data/plugins/music_service/squeezelite/squeezelite.service: No such file or directory
sed: can't read /data/plugins/music_service/squeezelite/squeezelite.service: No such file or directory
plugininstallend
```

I solved this by simply `mkdir /data/plugins/music_service/squeezelite` and working as expected.

**Comment by Saiyato** [comment]
Hi, you shouldn't 'just run' install.sh, instead use volumio plugin install, that way all necessary actions (like creating the folder) are taken care of ;)

see: https://volumio.github.io/docs/Plugin_System/Writing_A_Plugin.html

Not sure why installing from the store didn't work, a few tests on my machine installed it without problems. Any logs of that? The above errors are no bug, they just assume a different install method.

**Comment by st1nga** [comment]
I believe I have version 3 (Installed from Volumio-3.301-2022-06-09-pi.zip)

I am not sure what or where to get from the store, but it does not show up in plugins.
I to did sh ./install.sh as it did not say to not do that! And that is the normal way to install stuff :-)

When I do -bash-5.0# volumio plugin install

I get

This command will install the plugin on your device

 ================================ WARNING ====================================
 
This plugin is not verified by Volumio. Installing it is UNSAFE and can make your system UNSTABLE!
You are STRONGLY advised not to install plugins manually, better wait they are officially available.
 
 =============================================================================
? Do you want to install this plugin anyway? Yes
Compressing the plugin
Plugin succesfully compressed
/bin/mv: target '/tmp/plugins/squeezelite.zip' is not a directory
(node:2689) UnhandledPromiseRejectionWarning: Error: Command failed: /bin/mv *.zip /tmp/plugins/squeezelite.zip
/bin/mv: target '/tmp/plugins/squeezelite.zip' is not a directory

    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at /volumio/pluginhelper.js:778:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2689) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2689) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

and it hangs...

The issue would seem to be multiple .zip files...
-bash-5.0# ll *zip
-rw-r--r-- 1 root root 33712110 Aug 25 13:20 squeezelite.zip
-rw-r--r-- 1 root root  8145196 Aug 25 11:22 volumio-squeezelite-plugin.zip

**Comment by st1nga** [comment]
I removed the volumio-squeezelite-plugin.zip as it seems to be a zip of the files downloaded
I now get...

```
-bash-5.0# volumio plugin install

This command will install the plugin on your device

 ================================ WARNING ====================================
This plugin is not verified by Volumio. Installing it is UNSAFE and can make your system UNSTABLE!
You are STRONGLY advised not to install plugins manually, better wait they are officially available.
 
 =============================================================================
? Do you want to install this plugin anyway? Yes
Compressing the plugin
No modules found, running "npm install"
npm notice created a lockfile as package-lock.json. You should commit this file.
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin
nloading plugin at http://127.0.0.1:3000/plugin-serve/squeezelite.zip
```




And it hangs there, not sure what it is doing.
