### ISSUE TITLE
volumio 3 install fails

### ISSUE THREAD

**Issue by sideshowbob84** [Saiyato/volumio-squeezelite-plugin#8]
Hello,
thanks a lot for bringing squeezelite to volumio 3. I am on 3.178 on a pi zero w and tried to install the plugin. I am no pro, so maybe i did something wrong. I did:

```
git clone https://github.com/Saiyato/volumio-squeezelite-plugin.git
cd volumio-squeezelite-plugin
volumio plugin install
```

I get the following error:

```
This command will install the plugin on your device

Compressing the plugin
Plugin succesfully compressed
/bin/mv: target '/tmp/plugins/squeezelite.zip' is not a directory
child_process.js:655
    throw err;
    ^

Error: Command failed: /bin/mv *.zip /tmp/plugins/squeezelite.zip
/bin/mv: target '/tmp/plugins/squeezelite.zip' is not a directory

    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at install (/volumio/pluginhelper.js:765:9)
    at Object.<anonymous> (/volumio/pluginhelper.js:860:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(66) [Uint8Array] [
       47,  98, 105, 110,  47, 109, 118,  58,  32, 116,  97,
      114, 103, 101, 116,  32,  39,  47, 116, 109, 112,  47,
      112, 108, 117, 103, 105, 110, 115,  47, 115, 113, 117,
      101, 101, 122, 101, 108, 105, 116, 101,  46, 122, 105,
      112,  39,  32, 105, 115,  32, 110, 111, 116,  32,  97,
       32, 100, 105, 114, 101,  99, 116, 111, 114, 121,  10
    ]
  ],
  pid: 23539,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(66) [Uint8Array] [
     47,  98, 105, 110,  47, 109, 118,  58,  32, 116,  97,
    114, 103, 101, 116,  32,  39,  47, 116, 109, 112,  47,
    112, 108, 117, 103, 105, 110, 115,  47, 115, 113, 117,
    101, 101, 122, 101, 108, 105, 116, 101,  46, 122, 105,
    112,  39,  32, 105, 115,  32, 110, 111, 116,  32,  97,
     32, 100, 105, 114, 101,  99, 116, 111, 114, 121,  10
  ]
}
```

kind regards

**Comment by Saiyato** [comment]
You need additional packages to build plugins, so that will most like fail if you don't satisfy the dependencies.
Take a look here for easy installation: https://github.com/Saiyato/volumio-plugin-helper
Or read the Volumio documentation for the most up-to-date dependencies, there might have been changes in the meantime.
